In [1]:
import numpy as np
import random

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
from collections import OrderedDict

In [4]:
def reservoir_sampling(memory,k):
    '''
        Select k items from an array of length n
    '''
    
    batch_size = 10
    
    reservoir = []
    for i in range(batch_size):

        reservoir.append(memory[i])

    for i in range(batch_size,len(memory)):

        j= random.randrange(i + 1)

        if j < batch_size: # happens with prob j / i

            reservoir[j] = memory[i]
            
    return reservoir

In [5]:
memory = [i for i in range(100)]

In [6]:
res_sample = reservoir_sampling(memory,10)

In [7]:
res_sample

[58, 1, 49, 3, 41, 77, 12, 79, 14, 24]

In [9]:
torch.IntTensor(res_sample)

tensor([ 58,   1,  49,   3,  41,  77,  12,  79,  14,  24], dtype=torch.int32)

Test policy network with nll loss

In [80]:
class PolicyNetwork(nn.Module):
    """Actor (Policy) Model."""

    def __init__(self, state_size, action_size,seed):
        """Initialize parameters and build model.
        Params
        ======
            state_size (int): Dimension of each state
            action_size (int): Dimension of each action
            seed (int): Random seed
        """
        super(PolicyNetwork, self).__init__()
        self.action_size = action_size
        self.model = None
        self.seed = torch.manual_seed(seed)
        self.state_size = state_size
        self.init()


    def init(self):

        model = nn.Sequential(OrderedDict([
            ('ds1', nn.Linear(self.state_size, 64)),
            ('act1', nn.Sigmoid()),
            ('ds2', nn.Linear(64, self.action_size))

        ]))

        self.model = model.double()


    def forward(self, state):

        return self.model(state)


In [136]:
state = np.array([[1., 0., 0., 0.],
         [0., 1., 0., 0.]])

In [137]:
state = state.flatten()

In [138]:
state = torch.from_numpy(state).double()

In [139]:
state

tensor([ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.], dtype=torch.float64)

In [140]:
state.flatten()

AttributeError: 'Tensor' object has no attribute 'flatten'

In [141]:
PNetwork = PolicyNetwork(8,4,1)

In [142]:
predicted_actions = PNetwork(state)

In [163]:
predicted_actions.data.numpy()

array([ 0.61543252, -0.59251684,  0.33717609,  0.05624492])

In [144]:
predicted_actions.max()

tensor(0.6154, dtype=torch.float64)

In [145]:
F.softmax(predicted_actions.reshape((1,4)))

/Users/befeltingu/virtualenvs/DeepRL/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


tensor([[ 0.3806,  0.1137,  0.2881,  0.2176]], dtype=torch.float64)

In [146]:
actual_action = torch.from_numpy(np.array([0]))

In [151]:
actual_action

tensor([ 0])

In [152]:
predicted_actions

tensor([ 0.6154, -0.5925,  0.3372,  0.0562], dtype=torch.float64)

In [156]:
predicted_torch = torch.from_numpy(np.random.random((4,2)))

In [ ]:
actual_torch = torch.from_numpy

In [154]:
loss = F.nll_loss(F.softmax(predicted_actions.reshape((1,4))),actual_action)

/Users/befeltingu/virtualenvs/DeepRL/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [155]:
loss

tensor(-0.3806, dtype=torch.float64)

In [120]:
a = np.array([1,1,1])
b = np.array([0.0,0.0,0.0])

In [121]:
euclidean(a,b)

1.7320508075688772

In [164]:
current_policy = {
            "bet": 0,
            "check": 0,
            "call": 0,
            "fold": 0
        }

In [166]:
import json

In [169]:
json.dumps(current_policy,sort_keys=True)

'{"bet": 0, "call": 0, "check": 0, "fold": 0}'

In [165]:
json.ducurrent_policy

{'bet': 0, 'check': 0, 'call': 0, 'fold': 0}